_BASE_: "../base_retinanet_VG.yaml"
MODEL:
  META_ARCHITECTURE: "authorRetinaNet"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
OUTPUT_DIR: "./results/VG/retinanet/retinanet_author_r50_fpn_VG/"